language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get install -y bc
install:
  - cd src; ./autogen.sh; cd -
  - make -C src
env:
  global:
    - CONNLM_NO_OPT=1
  matrix:
    - CASE=1
    - CASE=2
script: 
  - source tools/shutils/shutils.sh
  - cd egs/tiny; shu-testing $CASE

