language: c
sudo: false
addons:
  apt:
    packages:
    - bc
compiler:
  - clang
  - gcc
install:
  - cd src; ./autogen.sh; cd -
  - make -C src
env:
  global:
    - CONNLM_NO_OPT=1
  matrix:
    - CASE=1
    - CASE=2
    - CASE=3
script: 
  - source tools/shutils/shutils.sh
  - if [ $CASE -eq 2 ]; then make -C src test; fi
  - if [ $CASE -eq 3 ]; then cd egs/selection; shu-testing; ret=$?; cd -; exit $ret; fi
  - cd egs/tiny; shu-testing $CASE
notifications:
  email:
    on_success: always
    on_failure: always
