language: c
sudo: false
# need to set this if wishing to dump core files
#sudo: required
addons:
  apt:
    packages:
    - bc
    - gdb
compiler:
  - clang
  - gcc
install:
  - cd src; ./autogen.sh; cd -
  - make -C src
before_script:
  - ulimit -c unlimited -S
after_failure:
  - COREFILE=$(find . -name "core*" | head -n 1)
  - if [[ -f "$COREFILE" ]]; then EXEFILE=$(strings "$COREFILE" | grep ^/ | tail -n 1); gdb -c "$COREFILE" "$EXEFILE" -ex "thread apply all bt" -ex "set pagination 0" -batch; fi

env:
  global:
    - CONNLM_NO_OPT=1
# need to set this if sudo: required
#    - CFLAGS=-mno-avx
  matrix:
    - CASE=1
    - CASE=2
    - CASE=3
    - CASE=4
    - CASE=5
    - CASE=6
    - CASE=7
    - CASE=8
    - CASE=9
    - CASE=10
script:
  - .travis/build.sh
notifications:
  email:
    on_success: always
    on_failure: always
branches:
  only:
    - master
    - develop
    - legacy
