var annotated_dup =
[
    [ "connlm_egs_t", "structconnlm__egs__t.html", "structconnlm__egs__t" ],
    [ "connlm_gen_opt_t", "structconnlm__gen__opt__t.html", "structconnlm__gen__opt__t" ],
    [ "connlm_model_opt_t", "structconnlm__model__opt__t.html", "structconnlm__model__opt__t" ],
    [ "connlm_t", "structconnlm__t.html", "structconnlm__t" ],
    [ "connlm_test_opt_t", "structconnlm__test__opt__t.html", "structconnlm__test__opt__t" ],
    [ "connlm_train_opt_t", "structconnlm__train__opt__t.html", "structconnlm__train__opt__t" ],
    [ "ffnn_model_opt_t", "structffnn__model__opt__t.html", "structffnn__model__opt__t" ],
    [ "ffnn_neuron_t", "structffnn__neuron__t.html", null ],
    [ "ffnn_t", "structffnn__t.html", "structffnn__t" ],
    [ "ffnn_train_opt_t", "structffnn__train__opt__t.html", "structffnn__train__opt__t" ],
    [ "hash_hist_t", "structhash__hist__t.html", "structhash__hist__t" ],
    [ "hash_range_t", "structhash__range__t.html", "structhash__range__t" ],
    [ "lbl_model_opt_t", "structlbl__model__opt__t.html", "structlbl__model__opt__t" ],
    [ "lbl_neuron_t", "structlbl__neuron__t.html", null ],
    [ "lbl_t", "structlbl__t.html", "structlbl__t" ],
    [ "lbl_train_opt_t", "structlbl__train__opt__t.html", "structlbl__train__opt__t" ],
    [ "maxent_model_opt_t", "structmaxent__model__opt__t.html", "structmaxent__model__opt__t" ],
    [ "maxent_neuron_t", "structmaxent__neuron__t.html", "structmaxent__neuron__t" ],
    [ "maxent_t", "structmaxent__t.html", "structmaxent__t" ],
    [ "maxent_train_opt_t", "structmaxent__train__opt__t.html", "structmaxent__train__opt__t" ],
    [ "output_neuron_t", "structoutput__neuron__t.html", "structoutput__neuron__t" ],
    [ "output_opt_t", "structoutput__opt__t.html", "structoutput__opt__t" ],
    [ "output_t", "structoutput__t.html", "structoutput__t" ],
    [ "param_arg_t", "structparam__arg__t.html", "structparam__arg__t" ],
    [ "param_t", "structparam__t.html", "structparam__t" ],
    [ "rnn_model_opt_t", "structrnn__model__opt__t.html", "structrnn__model__opt__t" ],
    [ "rnn_neuron_t", "structrnn__neuron__t.html", "structrnn__neuron__t" ],
    [ "rnn_t", "structrnn__t.html", "structrnn__t" ],
    [ "rnn_train_opt_t", "structrnn__train__opt__t.html", "structrnn__train__opt__t" ],
    [ "vocab_learn_opt_t", "structvocab__learn__opt__t.html", "structvocab__learn__opt__t" ],
    [ "vocab_opt_t", "structvocab__opt__t.html", "structvocab__opt__t" ],
    [ "vocab_t", "structvocab__t.html", "structvocab__t" ]
];