#!/bin/bash
#
# code from http://stackoverflow.com/questions/3462955/putting-git-hooks-into-repository
#

TRACKED_HOOK_DIR="$(git rev-parse --show-toplevel)/misc/git-hooks"

if [ -x $0.local ]; then
    $0.local "$@" || exit $?
fi
if [ -x "$TRACKED_HOOK_DIR/$(basename $0)" ]; then
    "$TRACKED_HOOK_DIR/$(basename $0)" "$@" || exit $?
fi
