#!/bin/bash
#

TOOL_DIR="$(git rev-parse --show-toplevel)/tools/"
REV_FILE=$TOOL_DIR/.git-revs
REPOS="stutils shutils"

cd $TOOL_DIR || exit 1

> $REV_FILE
for repo in $REPOS; do
  (cd $repo; echo "$repo: $(git rev-parse HEAD)" >> $REV_FILE) || exit 1
done

exit 0

